### ISSUE TITLE
Shaders glitching

### ISSUE THREAD

**Issue by WMAcademy** [exsstas/Raymarching-in-TD#1]
Hi, I'm following your tutorial series on Raymarching in TD and I found myself stuck with a bug with the shaders inside the 6th, 7th and 9th Containers COMP, basically those present some glitches without making any changes. Maybe this happens due to the fact that those script were made in older version of TD (i guess, idk). Can you help me? Thank you in advance for your time and for this amazing tutorial series.

![Immagine 2024-08-03 175604](https://github.com/user-attachments/assets/78777f6d-d39c-421c-bd58-563b34272d21)
![Immagine 2024-08-03 175622](https://github.com/user-attachments/assets/1d5c88fe-f50c-41d1-8787-1a1d7d603a20)
![Immagine 2024-08-03 175641](https://github.com/user-attachments/assets/4f215994-231c-42ed-923e-568fc8498451)

**Comment by exsstas** [comment]
Hi, thank you for letting me know. Here is a hot fix https://github.com/exsstas/Raymarching-in-TD/blob/master/tutorial%20-%20part%202%20(2024%20hotfix).toe
However, I didn't investigate fully difference between GLSL code interpretation in a newer versions, so it's very possible that something similar may occur in other examples aw well. Unfortunately don't have time now to go through all of my example files to fix it if needed
